/* Generated By:JavaCC: Do not edit this line. phpTreeConstants.java Version 5.0 */
package jjt;

public interface phpTreeConstants
{
  public int JJTPROGRAMAINICIO = 0;
  public int JJTCUERPOPROGRAMA = 1;
  public int JJTCUERPOCOMENTARIO = 2;
  public int JJTCLASE = 3;
  public int JJTCUERPOCLASE = 4;
  public int JJTCVARIABLES = 5;
  public int JJTTVARIABLE = 6;
  public int JJTASIGNACIONVAR = 7;
  public int JJTDECFUNCTION = 8;
  public int JJTCUERPOFUNCTION = 9;
  public int JJTCUERPOMATRIZ = 10;
  public int JJTPARAMETROSFOR = 11;
  public int JJTCUERPOFOR = 12;
  public int JJTCUERPOVECFOR = 13;
  public int JJTASIGNARMATVECT = 14;
  public int JJTIMPRIMIR = 15;
  public int JJTOPERACIONESARIT1 = 16;
  public int JJTOAR = 17;
  public int JJTORE = 18;
  public int JJTOLOG = 19;
  public int JJTPARAMETROSFUCTION = 20;
  public int JJTCUERPORETURN = 21;
  public int JJTCONSTRUCTOR = 22;
  public int JJTCUERPOCONSTRUCTOR = 23;
  public int JJTMINCLUDE = 24;
  public int JJTMETPARENT = 25;
  public int JJTMETTHIS = 26;
  public int JJTCUERPOIF = 27;
  public int JJTELSEIFS = 28;
  public int JJTPARAMETROSIF = 29;
  public int JJTNOTPARAMETROS = 30;
  public int JJTORE2 = 31;
  public int JJTOLOG2 = 32;
  public int JJTOAR2 = 33;
  public int JJTSENTENCIASIF = 34;
  public int JJTSENTENCIASW = 35;
  public int JJTSENTCASE = 36;
  public int JJTCUERPOCASE = 37;
  public int JJTIMPRIMIR2 = 38;
  public int JJTSENTENCIAWH = 39;
  public int JJTCUERPOWH = 40;
  public int JJTSENTENCIADOWH = 41;
  public int JJTSENTENCIAFOR = 42;
  public int JJTCUERPOFOR2 = 43;
  public int JJTMETODOMAIN = 44;
  public int JJTPARAMETROSMAIN = 45;


  public String[] jjtNodeName = {
    "ProgramaInicio",
    "CuerpoPrograma",
    "CuerpoComentario",
    "Clase",
    "CuerpoClase",
    "CVariables",
    "TVariable",
    "AsignacionVar",
    "DecFunction",
    "CuerpoFunction",
    "CuerpoMatriz",
    "ParametrosFOR",
    "CuerpoFor",
    "CuerpoVecFor",
    "AsignarMatVect",
    "Imprimir",
    "OperacionesArit1",
    "OAr",
    "ORe",
    "OLog",
    "ParametrosFuction",
    "CuerpoReturn",
    "Constructor",
    "CuerpoConstructor",
    "MInclude",
    "MetParent",
    "MetThis",
    "CuerpoIF",
    "Elseifs",
    "ParametrosIF",
    "NotParametros",
    "ORe2",
    "OLog2",
    "OAr2",
    "SentenciasIF",
    "SentenciaSW",
    "SentCase",
    "CuerpoCase",
    "Imprimir2",
    "SentenciaWh",
    "CuerpoWh",
    "SentenciaDoWh",
    "SentenciaFor",
    "CuerpoFor2",
    "MetodoMain",
    "ParametrosMain",
  };
}
/* JavaCC - OriginalChecksum=26e1294b18a146cbad050e7982995473 (do not edit this line) */
