/* Generated By:JavaCC: Do not edit this line. phpConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface phpConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 7;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 8;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 9;
  /** RegularExpression Id. */
  int NUM = 10;
  /** RegularExpression Id. */
  int ID = 11;
  /** RegularExpression Id. */
  int LETTER = 12;
  /** RegularExpression Id. */
  int CADENA = 13;
  /** RegularExpression Id. */
  int DEC = 14;
  /** RegularExpression Id. */
  int CARAC = 15;
  /** RegularExpression Id. */
  int TAGINICIO = 16;
  /** RegularExpression Id. */
  int TAGFIN = 17;
  /** RegularExpression Id. */
  int PCLASS = 18;
  /** RegularExpression Id. */
  int PVAR = 19;
  /** RegularExpression Id. */
  int PFUNCION = 20;
  /** RegularExpression Id. */
  int PFOR = 21;
  /** RegularExpression Id. */
  int PECHO = 22;
  /** RegularExpression Id. */
  int PRETURN = 23;
  /** RegularExpression Id. */
  int PNEW = 24;
  /** RegularExpression Id. */
  int PCONST = 25;
  /** RegularExpression Id. */
  int LLAVEA = 26;
  /** RegularExpression Id. */
  int LLAVEC = 27;
  /** RegularExpression Id. */
  int IGUAL = 28;
  /** RegularExpression Id. */
  int PUNTOCOMA = 29;
  /** RegularExpression Id. */
  int COMA = 30;
  /** RegularExpression Id. */
  int DOLAR = 31;
  /** RegularExpression Id. */
  int COMILLASIMPLE = 32;
  /** RegularExpression Id. */
  int COMILLADOBLE = 33;
  /** RegularExpression Id. */
  int PARA = 34;
  /** RegularExpression Id. */
  int PARC = 35;
  /** RegularExpression Id. */
  int MAYOR = 36;
  /** RegularExpression Id. */
  int MENOR = 37;
  /** RegularExpression Id. */
  int DECR = 38;
  /** RegularExpression Id. */
  int INC = 39;
  /** RegularExpression Id. */
  int CORCHA = 40;
  /** RegularExpression Id. */
  int CORCHC = 41;
  /** RegularExpression Id. */
  int POR = 42;
  /** RegularExpression Id. */
  int SUMA = 43;
  /** RegularExpression Id. */
  int RESTA = 44;
  /** RegularExpression Id. */
  int DIV = 45;
  /** RegularExpression Id. */
  int MOD = 46;
  /** RegularExpression Id. */
  int POTEN = 47;
  /** RegularExpression Id. */
  int IGUAL2 = 48;
  /** RegularExpression Id. */
  int IDENT = 49;
  /** RegularExpression Id. */
  int DIFE1 = 50;
  /** RegularExpression Id. */
  int DIFE2 = 51;
  /** RegularExpression Id. */
  int NOIDE = 52;
  /** RegularExpression Id. */
  int MENORI = 53;
  /** RegularExpression Id. */
  int MAYORI = 54;
  /** RegularExpression Id. */
  int LAND = 55;
  /** RegularExpression Id. */
  int LOR = 56;
  /** RegularExpression Id. */
  int LXOR = 57;
  /** RegularExpression Id. */
  int LNOT = 58;
  /** RegularExpression Id. */
  int LAND2 = 59;
  /** RegularExpression Id. */
  int LOR2 = 60;
  /** RegularExpression Id. */
  int AMP = 61;
  /** RegularExpression Id. */
  int ASIG = 62;
  /** RegularExpression Id. */
  int PUNTO = 63;
  /** RegularExpression Id. */
  int BARRA = 64;
  /** RegularExpression Id. */
  int SALTO = 65;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 1;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "<token of kind 6>",
    "\"*/\"",
    "\"*/\"",
    "<SINGLE_LINE_COMMENT>",
    "<NUM>",
    "<ID>",
    "<LETTER>",
    "<CADENA>",
    "<DEC>",
    "<CARAC>",
    "\"<?php\"",
    "\"?>\"",
    "\"class \"",
    "\"var \"",
    "\"function \"",
    "\"for \"",
    "\"echo \"",
    "\"return \"",
    "\"new \"",
    "\"function __construct\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\";\"",
    "\",\"",
    "\"$\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "\"(\"",
    "\")\"",
    "\">\"",
    "\"<\"",
    "\"--\"",
    "\"++\"",
    "\"[\"",
    "\"]\"",
    "\"*\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"%\"",
    "\"**\"",
    "\"==\"",
    "\"===\"",
    "\"!=\"",
    "\"<>\"",
    "\"!==\"",
    "\"<=\"",
    "\">=\"",
    "\"and \"",
    "\"or \"",
    "\"xor \"",
    "\"!\"",
    "\"&&\"",
    "\"||\"",
    "\"&\"",
    "\"->\"",
    "\".\"",
    "\"\\\\\"",
    "\"n \"",
  };

}
